# Generated by Django 6.0.6 on 2026-07-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Fiesta de la Vendimia 2023', max_length=200)),
                ('fecha', models.CharField(help_text='Ej: Marzo 2023', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Breve descripción del evento', null=True)),
                ('imagen', models.ImageField(help_text='Sube la foto del recuerdo aquí', upload_to='recuerdos/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
