# Generated by Django 6.0.6 on 2026-07-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recuerdo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vino',
            name='maridaje',
            field=models.CharField(blank=True, help_text='Ej: Ideal para carnes rojas y quesos maduros', max_length=200, null=True),
        ),
    ]
